#security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      scope: read,write
#      auto-approve-scopes: '.*'
#
#facebook:
#  client:
#    clientId: 233668646673605
#    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://graph.facebook.com/me
#github:
#  client:
#    clientId: bd1c0a783ccdd1c9b9e4
#    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#    accessTokenUri: https://github.com/login/oauth/access_token
#    userAuthorizationUri: https://github.com/login/oauth/authorize
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://api.github.com/user
#
#logging:
#  level:
#    org.springframework.security: DEBUG

#security:
#  oauth2:
#    client:
#      clientId: 1987125588172293
#      clientSecret: a23268f177ec243890ec22c4fddf971e
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me

# security:
#   oauth2:
#     client:
#       # From OIDC app
#       clientId: 0oaec146kqLJ9MPTv0h7
#       clientSecret: 5KUiAQLAgLXjKtxnAWh8c7c8r74BbEgd9N4iAfIM
#       # From Authorization Server's metadata
#       accessTokenUri: https://dev-460096.oktapreview.com/oauth2/default/v1/token
#       userAuthorizationUri: https://dev-460096.oktapreview.com/oauth2/default/v1/authorize
#       clientAuthenticationScheme: form
#       scope: openid profile email
#     resource:
#       # from your Auth Server's metadata, check .well-known/openid-configuration if not in .well-known/oauth-authorization-server
#       userInfoUri: https://dev-460096.oktapreview.com/oauth2/default/v1/userinfo
